name: Directory Listing

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare merge dir
        run: |
          mkdir -p public/tur

      - name: Copy tracked folders
        run: |
          cp -r dists public/tur/dists
          cp -r pool public/tur/pool

      - name: Generate index
        uses: CMSZ001/tur-mirror@directory-listing
        with:
          FOLDER: public

      - name: Install html-minifier
        run: |
          npm install -g html-minifier-terser

      - name: Minify HTML content
        run: |
          cp -r public/ dist/
          find dist -name "*.html" -exec html-minifier-terser --collapse-whitespace --remove-comments --minify-js true --minify-css false -o {} {} \;

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/tur

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
