name: Directory Listing

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. 创建目录
      - name: Prepare merge dir
        run: |
          mkdir -p public/tur

      # 2. 复制要发布的内容
      - name: Copy tracked folders
        run: |
          cp -r dists public/tur/dists
          cp -r pool public/tur/pool

      # 3. 生成目录索引
      - name: Generate index
        uses: CMSZ001/tur-mirror@directory-listing
        with:
          FOLDER: public

      # 4. 上传 Pages 构建产物
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/tur

      # 5. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
